services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infra\Serializer\:
        resource: '../../src/Infra/Serializer/'

    App\Domain\Serializer\QuestionSerializerInterface: '@App\Infra\Serializer\QuestionSerializer'
