App\Domain\Entity\Answer:
    type: entity
    table: answer
    id:
        id:
            type: string
            generator: { strategy: NONE }
    fields:
        label:
            type: string
    manyToOne:
        question:
            targetEntity: App\Domain\Entity\Question
            inversedBy: answers
