App\Domain\Entity\Recruiter:
    type: entity
    table: recruiter
    id:
        id:
            type: string
            generator: { strategy: NONE }
    fields:
        companyName:
            type: string
        email:
            type: string
        password:
            type: string
