parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\UI\Actions\:
        resource: '../src/UI/Actions/'
        tags: ['controller.service_arguments']

    App\App\CommandHandler\:
        resource: '../src/App/CommandHandler/'
        tags: ['messenger.message_handler']

    App\App\QueryFinder\:
        resource: '../src/App/QueryFinder/'
        tags: ['messenger.message_handler']
